#!/usr/bin/env bun
// scripts/sync-icon-shim.ts
//
// Generates shims/lucide-icons-2.js — the used-icons shim for
// @tamagui/lucide-icons-2 — by scanning the repo's actual imports.
//
// WHY IT EXISTS: metro.config.js runs with `unstable_enablePackageExports
// = false` (the CJS nuclear option — see that file for the zustand
// import.meta story). CJS resolution cannot tree-shake the icon barrel:
// importing ONE icon pulls all 3520 (measured: over a megabyte of
// minified bundle for a few dozen used icons). metro.config.js resolves
// the exact specifier '@tamagui/lucide-icons-2' to the generated shim,
// which re-exports only the used icons from their per-icon modules
// (Metro still picks the .native.js twin per platform on native).
//
// Chained before every expo command in package.json (and regenerated by
// metro.config.js if missing), so the shim can never go stale: add an
// icon import anywhere and the next build picks it up automatically.
//
// Exits 1 with a loud message if an imported icon has no per-icon module
// in node_modules (typo'd name) — that error should fail the build, not
// surface as a blank glyph.

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const ROOT = resolve(__dirname, '..');
const SHIM_JS = join(ROOT, 'shims/lucide-icons-2.js');
const SHIM_DTS = join(ROOT, 'shims/lucide-icons-2.d.ts');
const ICONS_DIR = join(ROOT, 'node_modules/@tamagui/lucide-icons-2/dist/esm/icons');

// Source roots scanned for barrel imports (everything except the shim
// itself, build output, and node_modules).
const SCAN_DIRS = [
  'app',
  'components',
  'constants',
  'context',
  'hooks',
  'lib',
  'navigation',
  'services',
  'shared',
  'stores',
  'utils',
];

const IMPORT_RE = /import\s+(?:type\s+)?\{([^}]+)\}\s*from\s*['"]@tamagui\/lucide-icons-2['"];?/g;

function listSourceFiles(dir: string): string[] {
  const out: string[] = [];
  if (!existsSync(dir)) return out;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listSourceFiles(full));
    else if (/\.(tsx?|jsx?)$/.test(entry.name)) out.push(full);
  }
  return out;
}

export function syncIconShim(): { icons: string[]; changed: boolean } {
  if (!existsSync(ICONS_DIR)) {
    console.error('  ✗ sync-icon-shim: node_modules/@tamagui/lucide-icons-2 is not installed.');
    process.exit(1);
  }

  const names = new Set<string>();
  for (const dir of SCAN_DIRS.map((d) => join(ROOT, d))) {
    for (const file of listSourceFiles(dir)) {
      const src = readFileSync(file, 'utf8');
      for (const m of src.matchAll(IMPORT_RE)) {
        for (const raw of m[1].split(',')) {
          const name = raw.replace(/^type\s+/, '').trim();
          // aliased imports (`X as Y`) ship under the ORIGINAL name
          const original = name.split(/\s+as\s+/)[0].trim();
          if (original.length > 0) names.add(original);
        }
      }
    }
  }

  const missing = [...names].filter((n) => !existsSync(join(ICONS_DIR, `${n}.mjs`)));
  if (missing.length > 0) {
    console.error(
      `  ✗ sync-icon-shim: imported icon(s) with no per-icon module in @tamagui/lucide-icons-2 (typo?):\n    ${missing.join(', ')}`,
    );
    process.exit(1);
  }

  const icons = [...names].sort();
  const js =
    '// GENERATED by scripts/sync-icon-shim.ts — do not edit by hand.\n' +
    '// Re-exports every @tamagui/lucide-icons-2 icon the repo imports,\n' +
    '// from per-icon modules (see that script for why the barrel cannot\n' +
    '// tree-shake under CJS resolution). Regenerated on every build.\n\n' +
    icons
      .map((n) => `export { ${n} } from '@tamagui/lucide-icons-2/dist/esm/icons/${n}.mjs';`)
      .join('\n') +
    '\n';

  const dts =
    '// GENERATED by scripts/sync-icon-shim.ts — do not edit by hand.\n' +
    '// Types for the used-icons runtime shim: the package\'s own barrel\n' +
    '// declarations, so every import site keeps its exact icon type.\n' +
    "export * from '@tamagui/lucide-icons-2';\n";

  const changed =
    !existsSync(SHIM_JS) ||
    !existsSync(SHIM_DTS) ||
    readFileSync(SHIM_JS, 'utf8') !== js ||
    readFileSync(SHIM_DTS, 'utf8') !== dts;
  if (changed) {
    mkdirSync(join(ROOT, 'shims'), { recursive: true });
    writeFileSync(SHIM_JS, js);
    writeFileSync(SHIM_DTS, dts);
  }
  return { icons, changed };
}

// Run directly (package.json chains it before every expo command).
if (import.meta.main) {
  const { icons, changed } = syncIconShim();
  console.log(
    `  sync-icon-shim: ${icons.length} icons${changed ? ' — shim regenerated' : ' — shim up to date'}`,
  );
}
